/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        amazon_blue: {
          light: "#232F3E",
          DEFAULT: "#131921",
        },
        "primary-container": "#232f3e",
        "outline-variant": "#c5c6cc",
        "secondary-fixed": "#ffdf9f",
        "inverse-surface": "#2e3132",
        "on-surface": "#191c1e",
        "on-surface-variant": "#44474c",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-tint": "#535f70",
        "secondary": "#795900",
        "surface-bright": "#f8f9fb",
        "surface": "#f8f9fb",
        "on-secondary-fixed-variant": "#5c4300",
        "on-tertiary-container": "#00ab76",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e1e2e4",
        "on-background": "#191c1e",
        "action-gradient-start": "#FDE68A",
        "error": "#ba1a1a",
        "background": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-high": "#e7e8ea",
        "on-secondary-container": "#6f5100",
        "surface-container-low": "#f3f4f6",
        "secondary-fixed-dim": "#f9bd22",
        "on-secondary": "#ffffff",
        "surface-dim": "#d9dadc",
        "inverse-on-surface": "#f0f1f3",
        "grade-gold": "#D97706",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-fixed": "#101c2b",
        "action-gradient-end": "#FBBF24",
        "tertiary-container": "#003623",
        "primary": "#0e1a28",
        "secondary-container": "#ffc329",
        "surface-card": "#FFFFFF",
        "inverse-primary": "#bbc7db",
        "tertiary": "#001f12",
        "surface-variant": "#e1e2e4",
        "on-secondary-fixed": "#261a00",
        "on-primary-fixed-variant": "#3c4858",
        "on-primary-container": "#8a97a9",
        "outline": "#75777c",
        "on-tertiary-fixed": "#002113",
        "action-border": "#FCD34D",
        "primary-fixed": "#d7e3f7",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#bbc7db",
        "tertiary-fixed-dim": "#4edea3",
        "text-meta": "#6B7280",
        "surface-container": "#edeef0"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "sm": "0.125rem"
      },
      spacing: {
        "container-margin": "2rem",
        "gutter": "1rem",
        "compact-gap": "0.25rem",
        "card-padding": "1.5rem",
        "stack-gap": "0.75rem",
        "margin-page": "1rem",
        "section-padding": "2rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem"
      },
      fontFamily: {
        "label-caps": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "title-sm": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "metadata": ["Inter"],
        "headline-sm": ["Inter"],
        "label-md": ["Inter"],
        "mono-label": ["Inter"],
        "product-title": ["Inter"],
        "display-price": ["Inter"],
        "status-badge": ["Inter"],
        "label-bold": ["Inter"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "metadata": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "mono-label": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "product-title": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "display-price": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "status-badge": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
