# Generated by Django 5.2.15 on 2026-06-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_size'),
        ('core', '0004_product_rating'),
    ]

    operations = [
    ]
