# Generated by Django 5.2.15 on 2026-06-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0004_order_size_0004_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='listing',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'Grade A – Like New'), ('B', 'Grade B – Very Good'), ('C', 'Grade C – Good'), ('D', 'Grade D – Heavy cosmetic damage (functional)'), ('E', 'Grade E – Functional defect / for parts'), ('F', 'Grade F – Not resellable (recycle)')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source',
            field=models.CharField(choices=[('new', 'New'), ('return', 'Amazon Return'), ('p2p', 'P2P (Individual)'), ('warehouse', 'Amazon Warehouse'), ('renewed', 'Amazon Renewed')], default='warehouse', max_length=20),
        ),
    ]
