# Generated by Django 4.2.13 on 2026-06-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_listing_images_alter_listing_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Grading'), ('listed', 'Listed'), ('paused', 'Paused'), ('delisted', 'Delisted'), ('sold', 'Sold'), ('donated', 'Donated'), ('recycled', 'Recycled'), ('warehouse_bound', 'Warehouse Bound'), ('refurb_scheduled', 'Refurb pickup scheduled'), ('refurbishing', 'Refurbishing at SPN center'), ('awaiting_demand', 'Held local · awaiting demand')], default='listed', max_length=20),
        ),
    ]
