# Generated by Django 4.2.13 on 2026-06-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_listing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('rating', models.IntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField(blank=True)),
                ('verified_purchase', models.BooleanField(default=True)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('source_asin', models.CharField(blank=True, default='', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product')),
            ],
            options={
                'ordering': ['-helpful_votes', '-review_date'],
            },
        ),
    ]
