# Generated by Django 4.2.13 on 2026-06-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_listing_indexes'),
        ('core', '0009_product_fit_signal_product_review_summary'),
    ]

    operations = [
    ]
