# Generated by Django 4.2.13 on 2026-07-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_images_user_address_user_phone'),
        ('core', '0011_user_is_seller_user_store_name'),
    ]

    operations = [
    ]
